In [4]:
#Running Foo w/ different parameters 
import asyncio

async def foo (param):
    await asyncio.sleep(1)
    print(f"Task with param {param} completed")
    return param

async def main():
    results =  await asyncio.gather (foo(1),foo(2),foo(3),foo(4))
    print ("Results: ", results)

await main() 





Task with param 1 completed
Task with param 3 completed
Task with param 2 completed
Task with param 4 completed
Results:  [1, 2, 3, 4]


In [3]:
#Running Foo w/ different parameters 
import asyncio

async def foo (param):
    await asyncio.sleep(5-param)
    print(f"Task with param {param} completed")
    return param

async def main():
    results =  await asyncio.gather (foo(1),foo(2),foo(3),foo(4))
    print ("Results: ", results)

await main() 





Task with param 4 completed
Task with param 3 completed
Task with param 2 completed
Task with param 1 completed
Results:  [1, 2, 3, 4]


In [6]:
# Timing stuff...
import asyncio
import time

async def say_after(delay, what):
    await asyncio.sleep(delay)
    print(what)

async def main():
    print(f"started at {time.strftime('%X')}")

    await say_after(1, 'hello')
    await say_after(2, 'world')

    print(f"finished at {time.strftime('%X')}")

await main()

started at 11:50:01
hello
world
finished at 11:50:04


In [46]:
#Using Foo format
import asyncio

# Dummy matrices for example 
A_NW, A_NE, A_SW, A_SE = 1, 2, 3, 4
B_NW, B_NE, B_SW, B_SE = 5, 6, 7, 8

async def quadrant(param, A_NW, A_NE, A_SW, A_SE, B_NW, B_NE, B_SW, B_SE):
    await asyncio.sleep(1)
    print(f"On Quadrant: {param}")
    return A_NW, A_NE, A_SW, A_SE, B_NW, B_NE, B_SW, B_SE

async def main():
    results = await asyncio.gather(
        quadrant(1, A_NW, A_NE, A_SW, A_SE, B_NW, B_NE, B_SW, B_SE),
        quadrant(2, A_NW, A_NE, A_SW, A_SE, B_NW, B_NE, B_SW, B_SE),
        quadrant(3, A_NW, A_NE, A_SW, A_SE, B_NW, B_NE, B_SW, B_SE),
        quadrant(4, A_NW, A_NE, A_SW, A_SE, B_NW, B_NE, B_SW, B_SE)
    )
    print("Results: ", results)

await main()  


On Quadrant: 1
On Quadrant: 3
On Quadrant: 2
On Quadrant: 4
Results:  [(1, 2, 3, 4, 5, 6, 7, 8), (1, 2, 3, 4, 5, 6, 7, 8), (1, 2, 3, 4, 5, 6, 7, 8), (1, 2, 3, 4, 5, 6, 7, 8)]


In [4]:
# Now applying actual summer code
import asyncio
import numpy as np

#Two 16x16 matrices with random integers
A = np.random.randint(0, 10, (16, 16))
B = np.random.randint(0, 10, (16, 16))

# Function to divide a matrix into quadrants
def divide_into_quadrants(matrix):
    NW = matrix[:8, :8]  # Top-left 8x8
    NE = matrix[:8, 8:]  # Top-right 8x8
    SW = matrix[8:, :8]  # Bottom-left 8x8
    SE = matrix[8:, 8:]  # Bottom-right 8x8
    return NW, NE, SW, SE

# Divide both A and B into quadrants
A_NW, A_NE, A_SW, A_SE = divide_into_quadrants(A)
B_NW, B_NE, B_SW, B_SE = divide_into_quadrants(B)

# function for multiplication and summation
async def quadrant(param, A_q1, A_q2, B_q1, B_q2):
    await asyncio.sleep(1)  # Simulate some delay
    print(f"Processing Quadrant: {param}")

    result1 = np.dot(A_q1, B_q1)
    result2 = np.dot(A_q2, B_q2)
    result = result1 + result2
    
    return result

async def main():
    # matrix multiplications and summations concurrently
    results = await asyncio.gather(
        # C_NW = A_NW * B_NW + A_SW * B_NE
        quadrant("C_NW", A_NW, A_SW, B_NW, B_NE),
        # C_NE = A_NW * B_NE + A_SW * B_SE
        quadrant("C_NE", A_NW, A_SW, B_NE, B_SE),
        # C_SW = A_SW * B_NW + A_SE * B_NE
        quadrant("C_SW", A_SW, A_SE, B_NW, B_NE),
        # C_SE = A_SW * B_NE + A_SE * B_SE
        quadrant("C_SE", A_SW, A_SE, B_NE, B_SE)
    )

    # putting the results into the quadrants
    C_NW, C_NE, C_SW, C_SE = results

    # 16x16 result matrix
    C = np.block([[C_NW, C_NE], [C_SW, C_SE]])

    # Print the result
    print("Quadrant results:")
    print("C_NW:\n", C_NW)
    print("C_NE:\n", C_NE)
    print("C_SW:\n", C_SW)
    print("C_SE:\n", C_SE)
    print("Complete Result Matrix C:\n", C)

await main()


Processing Quadrant: C_NW
Processing Quadrant: C_SW
Processing Quadrant: C_NE
Processing Quadrant: C_SE
Quadrant results:
C_NW:
 [[427 289 411 350 423 382 429 351]
 [356 306 387 381 283 423 394 399]
 [202 225 253 323 243 238 319 272]
 [388 265 355 357 334 326 369 315]
 [372 298 318 368 282 403 425 342]
 [252 216 235 224 228 220 288 148]
 [343 265 350 379 385 331 439 351]
 [422 352 351 305 326 395 382 373]]
C_NE:
 [[395 355 263 398 366 397 324 319]
 [428 321 266 398 348 432 425 318]
 [263 195 260 317 175 374 236 256]
 [360 364 238 375 298 425 295 301]
 [381 310 203 388 285 416 372 282]
 [219 203 105 238 158 179 210 177]
 [402 293 327 407 308 482 329 340]
 [442 334 286 373 347 394 361 326]]
C_SW:
 [[472 350 425 484 440 483 535 444]
 [373 291 382 416 399 341 451 358]
 [259 213 253 304 241 257 357 256]
 [423 320 360 355 340 406 432 367]
 [429 334 457 473 379 451 504 487]
 [273 198 198 263 156 312 253 337]
 [383 240 342 309 332 325 358 323]
 [290 343 236 255 268 311 286 322]]
C_SE:
 [[486 3

In [68]:
#Using Yield to help save memory and time

import numpy as np
import asyncio

# Two 16x16 matrices with random integers
A = np.random.randint(0, 10, (16, 16))
B = np.random.randint(0, 10, (16, 16))

# Function to divide a matrix into quadrants
def divide_into_quadrants(matrix):
    NW = matrix[:8, :8]  # Top-left 8x8
    NE = matrix[:8, 8:]  # Top-right 8x8
    SW = matrix[8:, :8]  # Bottom-left 8x8
    SE = matrix[8:, 8:]  # Bottom-right 8x8
    return NW, NE, SW, SE

# Divide both A and B into quadrants
A_NW, A_NE, A_SW, A_SE = divide_into_quadrants(A)
B_NW, B_NE, B_SW, B_SE = divide_into_quadrants(B)

# Generator function for multiplication and summation
async def quadrant(param, A_q1, A_q2, B_q1, B_q2):
    print(f"Processing Quadrant: {param}")
    
    await asyncio.sleep(1)

    # First multiplication
    result1 = np.dot(A_q1, B_q1)
    yield result1  # Yield control back to the generator
    
    await asyncio.sleep(1)

    result2 = np.dot(A_q2, B_q2)
    yield result2  

# Async generator
async def obtain_quadrant(param, A_q1, A_q2, B_q1, B_q2):
    get = quadrant(param, A_q1, A_q2, B_q1, B_q2)
    
    result1 = await get.__anext__()    #async iteration, await the next item asynchro...
    
    result2 = await get.__anext__()
    
    return result1 + result2

async def main():
    # quadrant computations happening concurrently using gather
    results = await asyncio.gather(
        obtain_quadrant("C_NW", A_NW, A_SW, B_NW, B_NE),
        obtain_quadrant("C_NE", A_NW, A_SW, B_NE, B_SE),
        obtain_quadrant("C_SW", A_SW, A_SE, B_NW, B_NE),
        obtain_quadrant("C_SE", A_SW, A_SE, B_NE, B_SE)
    )

    # Putting the results into the quadrants
    C_NW, C_NE, C_SW, C_SE = results

    # 16x16 matrix
    C = np.block([[C_NW, C_NE], [C_SW, C_SE]])

    print("Quadrant results:")
    print("C_NW:\n", C_NW)
    print("C_NE:\n", C_NE)
    print("C_SW:\n", C_SW)
    print("C_SE:\n", C_SE)
    print("Complete Result Matrix C:\n", C)

await main()


Processing Quadrant: C_NW
Processing Quadrant: C_NE
Processing Quadrant: C_SW
Processing Quadrant: C_SE
Quadrant results:
C_NW:
 [[241 346 227 297 340 341 327 249]
 [323 309 271 398 429 352 376 223]
 [286 362 279 322 382 368 369 286]
 [260 287 253 326 343 352 334 248]
 [147 197 193 193 274 202 210 213]
 [308 340 247 265 456 333 354 365]
 [297 393 333 348 437 449 345 344]
 [331 379 298 377 478 430 404 344]]
C_NE:
 [[254 368 308 423 431 342 281 418]
 [332 240 343 361 467 313 316 413]
 [291 341 330 440 453 333 338 388]
 [313 283 293 312 385 308 350 274]
 [168 171 155 245 300 204 224 187]
 [322 337 398 518 552 377 399 348]
 [366 352 343 464 525 421 400 379]
 [374 394 366 542 551 422 435 444]]
C_SW:
 [[205 328 241 283 341 303 305 252]
 [259 292 212 258 375 345 333 250]
 [328 307 292 364 423 353 374 260]
 [199 251 195 229 283 273 277 210]
 [268 301 199 301 316 278 376 213]
 [292 325 307 369 361 299 326 303]
 [297 321 243 317 347 318 351 252]
 [303 352 257 332 370 353 373 311]]
C_SE:
 [[222 2

notes about generators
- a generator is a special type of function that can be paused and resumed during execution, which allows it to yield multiple results over time rather than returning a single value at once. This is useful when you need to process large amounts of data incrementally

a normal function runs from start to finish and returns a value using return keyword. Once it returns, the function is done and cannot continue. 

A generator uses yield instead of return. When a generator function reaches a yield statement, it pauses and returns the values, so the next time you call the genorator, it resumes from where it left of.

SO IS IT THE SAME AS AWAIT?

Asyncronous generator 
- is a generator that works in an async function. It can yield values asyncrounously using away to pause the execution, allowing other async tasks to run concurr durring pauses, 
- what it a generator is the use of yield, instead of returning all results at once this function yields intermediate results one by one
- the await allows the function to pause when running, wait for a async operation like sleep(1), and then resumes when operation is done

- so yield is for for loops? since you can iterate and come back when u need it ?
- you need await if your actually waiting for network requests or file reads, API calls etc
- when your only yielding data values and dont need to wait for external operations use yield
